name: Artifacts

on:
    push:
        branches: [workflow6-artifacts]

env:
    ARTIFACT_NAME: cprogram
    FILE_NAME: main
    UPLOAD_PATH: ./main

jobs:
    build:
        name: "Compile main.c"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3
              with:
                  repository: jmoyano/cautious-meme
                  ref: main
            - name: "Compile"
              run: gcc main.c -o ${{ env.FILE_NAME }}
            - name: "Upload artifact"
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ env.ARTIFACT_NAME }}
                  path: ${{ env.UPLOAD_PATH }}
    test:
        name: "Test program"
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: "Download artifact"
              uses: actions/download-artifact@v3
              with:
                  name: ${{ env.ARTIFACT_NAME }}
            - name: Print directory
              run: ls
            - name: Test program
              run: |
                  chmod +x ./main
                  ./main
                  exit_code=$?
                  if [ $exit_code -eq 0 ]; then echo "Éxito"; else echo "Error"; fi;
