name: Second

on:
  push:
    branches:
      - workflows2

jobs:
  trabajo1:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: python eati.py "Workflow" "Dependencies"
  
  trabajo2:
    runs-on: windows-2019
    steps:
      - run: Get-Command
  
  trabajo3:
    runs-on: ubuntu-latest
    needs: [ trabajo1, trabajo2 ]
    steps:
      - run: env
  
  trabajo4:
    runs-on: ubuntu-latest
    steps:
      - run: /etc/*release
  
  trabajo5:
    runs-on: ubuntu-latest
    needs: [ trabajo3, trabajo4 ]
    steps:
      - run: echo "Fin workflow"