on:
    push:
        branch: [workflow5-secret]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Print secret
              run: echo ${{ secrets.SECRET_VARIABLE }}
